# Generated by Django 3.1.2 on 2020-10-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201031_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_url',
            field=models.URLField(default='https://bitsofco.de/content/images/2018/12/broken-1.png', max_length=100),
        ),
    ]
